import Head from "next/head";
import styles from "@/styles/Home.module.css";

import {
	FaTwitter as Twitter,
	FaGithub as Github,
	FaStackOverflow as StackOverflow,
	FaMedium as Medium,
	FaLinkedinIn as Linkedin,
} from "react-icons/fa";

export default function Home() {
	return (
		<>
			<Head>
				<title>Dhanuka Perera</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className="container">
					<div className="my-5"></div>
					<div className="display-3" style={{ color: "#FF8A00" }}>
						<span style={{ color: "white" }}>Hello, I'm</span>{" "}
						<br />
						Dhanuka.
					</div>
					<div className="h1 code mt-4 mb-3">async {"{"}</div>
					<div className="text-muted mx-5 my-4 h3 text-justify info">
						Hey, I am Software Engineer with 5+ years of experience
						in developing web, mobile, API, and Serverless
						applications. Expertise in React, Gatsby, React Native,
						Next JS, HTML, CSS, Angular, and TypeScript. Dedicated
						to delivering high-quality code that meets client
						requirements and industry standards.
					</div>
					<div className="h1 code mt-2 mb-3">{"}"}</div>
					<div className="h1 mt-5">
						<a
							className="mr-5 icon"
							href="https://twitter.com/dhanukasp"
						>
							<Twitter />
						</a>

						<a
							className="mr-5 icon"
							href="https://stackoverflow.com/users/5923069/dhanuka-perera"
						>
							<StackOverflow />
						</a>

						<a
							className="mr-5 icon"
							href="https://github.com/dhanukaperera"
						>
							<Github />
						</a>
						<a
							className="mr-5 icon"
							href="https://medium.com/@dhanukaperera"
						>
							<Medium />
						</a>
						<a
							className="mr-5 icon"
							href="https://www.linkedin.com/in/dhanukaperera/"
						>
							<Linkedin />
						</a>
					</div>
				</div>
			</main>
		</>
	);
}
